// AUTO-GENERATED — do not edit by hand.
//
// Generated by `mcp__supabase__generate_typescript_types` against the live
// project schema (project id `etcaodglvcspcmwecyxq`).
//
// Regenerate after any DDL migration:
//   - run the migration via supabase MCP `apply_migration`
//   - run the MCP `generate_typescript_types` tool
//   - replace this file with the output
//
// Hand-written domain types (e.g. union narrowings on `status`/`tag` columns
// that have CHECK constraints in SQL but appear as `string` here) live in
// the consuming module (e.g. `lib/supabase/feedback.ts`, `lib/supabase/errors.ts`)
// and use `Omit<Tables<"...">, "status"> & { status: MyUnion }` pattern.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      app_errors: {
        Row: {
          admin_notes: string | null
          context: Json | null
          created_at: string
          id: string
          message: string
          page_url: string | null
          source: string
          stack: string | null
          status: string
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          admin_notes?: string | null
          context?: Json | null
          created_at?: string
          id?: string
          message: string
          page_url?: string | null
          source: string
          stack?: string | null
          status?: string
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          admin_notes?: string | null
          context?: Json | null
          created_at?: string
          id?: string
          message?: string
          page_url?: string | null
          source?: string
          stack?: string | null
          status?: string
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      campaign_members: {
        Row: {
          campaign_id: string
          id: string
          joined_at: string
          role: string
          user_id: string
        }
        Insert: {
          campaign_id: string
          id?: string
          joined_at?: string
          role?: string
          user_id: string
        }
        Update: {
          campaign_id?: string
          id?: string
          joined_at?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaign_members_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      campaigns: {
        Row: {
          created_at: string
          description: string
          id: string
          invite_code: string
          name: string
          owner_id: string
          system_id: string
        }
        Insert: {
          created_at?: string
          description?: string
          id?: string
          invite_code?: string
          name: string
          owner_id: string
          system_id: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          invite_code?: string
          name?: string
          owner_id?: string
          system_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaigns_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaigns_system_id_fkey"
            columns: ["system_id"]
            isOneToOne: false
            referencedRelation: "game_systems"
            referencedColumns: ["id"]
          },
        ]
      }
      character_content_refs: {
        Row: {
          character_id: string
          choice_source: string | null
          content_id: string
          content_version: number
          context: Json
          created_at: string
          id: string
        }
        Insert: {
          character_id: string
          choice_source?: string | null
          content_id: string
          content_version?: number
          context?: Json
          created_at?: string
          id?: string
        }
        Update: {
          character_id?: string
          choice_source?: string | null
          content_id?: string
          content_version?: number
          context?: Json
          created_at?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "character_content_refs_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "character_content_refs_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_definitions"
            referencedColumns: ["id"]
          },
        ]
      }
      character_inventory: {
        Row: {
          attuned: boolean
          character_id: string
          content_id: string | null
          content_type: string
          created_at: string
          custom_data: Json | null
          equipped: boolean
          id: string
          name: string
          notes: string | null
          quantity: number
          sort_order: number
        }
        Insert: {
          attuned?: boolean
          character_id: string
          content_id?: string | null
          content_type?: string
          created_at?: string
          custom_data?: Json | null
          equipped?: boolean
          id?: string
          name: string
          notes?: string | null
          quantity?: number
          sort_order?: number
        }
        Update: {
          attuned?: boolean
          character_id?: string
          content_id?: string | null
          content_type?: string
          created_at?: string
          custom_data?: Json | null
          equipped?: boolean
          id?: string
          name?: string
          notes?: string | null
          quantity?: number
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "character_inventory_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "character_inventory_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_definitions"
            referencedColumns: ["id"]
          },
        ]
      }
      character_spells: {
        Row: {
          always_prepared: boolean
          character_id: string
          class_slug: string
          content_id: string | null
          created_at: string
          custom_data: Json | null
          id: string
          in_spellbook: boolean
          is_known: boolean
          is_prepared: boolean
          name: string
          source: string
        }
        Insert: {
          always_prepared?: boolean
          character_id: string
          class_slug: string
          content_id?: string | null
          created_at?: string
          custom_data?: Json | null
          id?: string
          in_spellbook?: boolean
          is_known?: boolean
          is_prepared?: boolean
          name: string
          source?: string
        }
        Update: {
          always_prepared?: boolean
          character_id?: string
          class_slug?: string
          content_id?: string | null
          created_at?: string
          custom_data?: Json | null
          id?: string
          in_spellbook?: boolean
          is_known?: boolean
          is_prepared?: boolean
          name?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "character_spells_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "character_spells_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_definitions"
            referencedColumns: ["id"]
          },
        ]
      }
      characters: {
        Row: {
          archived: boolean
          base_stats: Json
          campaign_id: string | null
          choices: Json
          created_at: string
          id: string
          level: number
          name: string
          narrative: Json
          narrative_rich: Json
          state: Json
          system_id: string
          user_id: string
          visibility: string
        }
        Insert: {
          archived?: boolean
          base_stats?: Json
          campaign_id?: string | null
          choices?: Json
          created_at?: string
          id?: string
          level?: number
          name: string
          narrative?: Json
          narrative_rich?: Json
          state?: Json
          system_id: string
          user_id: string
          visibility?: string
        }
        Update: {
          archived?: boolean
          base_stats?: Json
          campaign_id?: string | null
          choices?: Json
          created_at?: string
          id?: string
          level?: number
          name?: string
          narrative?: Json
          narrative_rich?: Json
          state?: Json
          system_id?: string
          user_id?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "characters_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "characters_system_id_fkey"
            columns: ["system_id"]
            isOneToOne: false
            referencedRelation: "game_systems"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "characters_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      content_definitions: {
        Row: {
          content_type: string
          created_at: string
          data: Json
          effects: Json
          id: string
          name: string
          owner_id: string | null
          scope: string
          slug: string
          source: string
          system_id: string
          version: number
        }
        Insert: {
          content_type: string
          created_at?: string
          data?: Json
          effects?: Json
          id?: string
          name: string
          owner_id?: string | null
          scope?: string
          slug: string
          source?: string
          system_id: string
          version?: number
        }
        Update: {
          content_type?: string
          created_at?: string
          data?: Json
          effects?: Json
          id?: string
          name?: string
          owner_id?: string | null
          scope?: string
          slug?: string
          source?: string
          system_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "content_definitions_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_definitions_system_id_fkey"
            columns: ["system_id"]
            isOneToOne: false
            referencedRelation: "game_systems"
            referencedColumns: ["id"]
          },
        ]
      }
      content_shares: {
        Row: {
          campaign_id: string
          content_id: string
          id: string
          shared_at: string
          shared_by: string
        }
        Insert: {
          campaign_id: string
          content_id: string
          id?: string
          shared_at?: string
          shared_by: string
        }
        Update: {
          campaign_id?: string
          content_id?: string
          id?: string
          shared_at?: string
          shared_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_shares_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_shares_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_definitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_shares_shared_by_fkey"
            columns: ["shared_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      content_type_shares: {
        Row: {
          campaign_id: string
          content_type_id: string
          id: string
          shared_at: string
          shared_by: string
        }
        Insert: {
          campaign_id: string
          content_type_id: string
          id?: string
          shared_at?: string
          shared_by: string
        }
        Update: {
          campaign_id?: string
          content_type_id?: string
          id?: string
          shared_at?: string
          shared_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_type_shares_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_type_shares_content_type_id_fkey"
            columns: ["content_type_id"]
            isOneToOne: false
            referencedRelation: "custom_content_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_type_shares_shared_by_fkey"
            columns: ["shared_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      content_versions: {
        Row: {
          changelog: string
          content_id: string
          created_at: string
          data_snapshot: Json
          effects_snapshot: Json
          id: string
          version: number
        }
        Insert: {
          changelog?: string
          content_id: string
          created_at?: string
          data_snapshot: Json
          effects_snapshot?: Json
          id?: string
          version: number
        }
        Update: {
          changelog?: string
          content_id?: string
          created_at?: string
          data_snapshot?: Json
          effects_snapshot?: Json
          id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "content_versions_content_id_fkey"
            columns: ["content_id"]
            isOneToOne: false
            referencedRelation: "content_definitions"
            referencedColumns: ["id"]
          },
        ]
      }
      custom_content_types: {
        Row: {
          allow_multiple: boolean
          description: string
          entry_conditions: Json
          has_progression: boolean
          id: string
          name: string
          owner_id: string
          scope: string
          slug: string
          system_id: string
          version: number
        }
        Insert: {
          allow_multiple?: boolean
          description?: string
          entry_conditions?: Json
          has_progression?: boolean
          id?: string
          name: string
          owner_id: string
          scope?: string
          slug: string
          system_id: string
          version?: number
        }
        Update: {
          allow_multiple?: boolean
          description?: string
          entry_conditions?: Json
          has_progression?: boolean
          id?: string
          name?: string
          owner_id?: string
          scope?: string
          slug?: string
          system_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "custom_content_types_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "custom_content_types_system_id_fkey"
            columns: ["system_id"]
            isOneToOne: false
            referencedRelation: "game_systems"
            referencedColumns: ["id"]
          },
        ]
      }
      feedback: {
        Row: {
          admin_notes: string | null
          created_at: string
          id: string
          page_url: string | null
          status: string
          tag: string | null
          text: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          admin_notes?: string | null
          created_at?: string
          id?: string
          page_url?: string | null
          status?: string
          tag?: string | null
          text: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          admin_notes?: string | null
          created_at?: string
          id?: string
          page_url?: string | null
          status?: string
          tag?: string | null
          text?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: []
      }
      game_systems: {
        Row: {
          created_at: string
          expression_context: Json
          id: string
          name: string
          schema_definition: Json
          slug: string
          status: string
          version_label: string
        }
        Insert: {
          created_at?: string
          expression_context?: Json
          id?: string
          name: string
          schema_definition?: Json
          slug: string
          status?: string
          version_label?: string
        }
        Update: {
          created_at?: string
          expression_context?: Json
          id?: string
          name?: string
          schema_definition?: Json
          slug?: string
          status?: string
          version_label?: string
        }
        Relationships: []
      }
      npcs: {
        Row: {
          character_id: string
          created_at: string
          created_by: string
          description: Json
          id: string
          metadata: Json
          name: string
          portrait_url: string | null
          relationship: string | null
          visibility: string
        }
        Insert: {
          character_id: string
          created_at?: string
          created_by: string
          description?: Json
          id?: string
          metadata?: Json
          name: string
          portrait_url?: string | null
          relationship?: string | null
          visibility?: string
        }
        Update: {
          character_id?: string
          created_at?: string
          created_by?: string
          description?: Json
          id?: string
          metadata?: Json
          name?: string
          portrait_url?: string | null
          relationship?: string | null
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "npcs_character_id_fkey"
            columns: ["character_id"]
            isOneToOne: false
            referencedRelation: "characters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "npcs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string
          display_name: string
          id: string
          preferences: Json
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string
          id: string
          preferences?: Json
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string
          id?: string
          preferences?: Json
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      patch_character_state: {
        Args: { character_id: string; state_patch: Json }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
